import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Task Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='h-screen flex'>
        <div className='w-64 px-4 py-4 border-r'>
          <div>
            <img src="/images/logo.svg" alt="Logo" className='w-52' />
          </div>
          <nav className='mt-8 px-6'>
            <h3 className='text-sm font-semibold text-gray-600  tracking-wide uppercase'>Dasboard</h3>
            <div className='mt-4 -mx-3'>
              <a href='#' className='flex item-center px-3 py-2 justify-between'>
                <span className='text-sm font-medium text-gray-700'>Anasayfa</span>
                <span className='text-xs font-extrabold text-gray-700'>23</span>
              </a>
              <a href='#' className='flex item-center px-3 py-2 justify-between'>
                <span className='text-sm font-medium text-gray-700'>Yapılacak İşler</span>
                <span className='text-xs font-extrabold text-gray-700'>2</span>
              </a>
              <a href='#' className='flex item-center px-3 py-2 justify-between rounded-2xl bg-gradient-to-r from-cyan-500 to-blue-500'>
                <span className='text-sm font-medium text-white'>Tamamlanan İşler</span>
                <span className='text-xs font-extrabold text-white'>18</span>
              </a>
            </div>

            <div className='-mx-3'>
              <a href='#' className='flex item-center px-3 py-2 justify-between'>
                <span className='text-sm font-medium text-gray-700'>Yeni Ticket </span>
                <span className='text-xs font-extrabold text-gray-700'>23</span>
              </a>
              <a href='#' className='flex item-center px-3 py-2 justify-between'>
                <span className='text-sm font-medium text-gray-700'>Hesap Bilgileri</span>
                <span className='text-xs font-extrabold text-gray-700'>2</span>
              </a>

            </div>
          </nav>
        </div>



        <div className='flex-1 min-w-0 bg-gray-100'>
          <header className='flex flex-col px-6 mt-3 border-b border-gray-200'>
            <div className='flex justify-between items-center py-3'>
              <div className='relative w-64 ml-4'>
                <span className='absolute inset-y-0 left-0 flex items-center pl-3'>
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-4 w-4text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                  </svg></span>
                <input className='block w-full h-10 text-sm border-gray-400 rounded-md py-2 pl-10 pr-4 focus:placeholder-gray-400 active:placeholder-gray-400 placeholder-gray-400'
                  placeholder='Arama Yap...' /></div>

              <div className='flex items-center'>

                <button className='bg-gray-200 p-1 rounded-2xl'>
                  <span className='py-3 px-3 text-sm font-bold flex items-center'>
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-11a1 1 0 10-2 0v2H7a1 1 0 100 2h2v2a1 1 0 102 0v-2h2a1 1 0 100-2h-2V7z" clipRule="evenodd" />
                    </svg>
                    Yeni Ticket Oluştur</span>
                </button>

                <button className='pl-3'>
                  <svg xmlns="http://www.w3.org/2000/svg" className="w-8 h-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
                  </svg>
                </button>



                <button className='pl-3'>
                  <img src="/images/avatar.jpg" className='w-8 h-8 rounded-full object-cover' alt="" />
                </button>
              </div>
            </div>

          </header>
          <div>Main</div>
        </div>
      </div>
    </>
  )
}
